### ISSUE TITLE
大佬，弄成同步盘撒，这样可以在Ubuntu上跑

### ISSUE THREAD

**Issue by user1121114685** [gawwo/fake115-go#1]

**Comment by gawwo** [comment]
本身是有完整的目录结构，改造一下，监控具体的文件夹就能达到同步盘的效果。
不过最初的目的是达到雷达一样效果的资源分享，还需要改造些地方。

**Comment by user1121114685** [comment]
> 本身是有完整的目录结构，改造一下，监控具体的文件夹就能达到同步盘的效果。
> 不过最初的目的是达到雷达一样效果的资源分享，还需要改造些地方。

我也会GO，大佬加我交流下。

**Comment by user1121114685** [comment]
> 本身是有完整的目录结构，改造一下，监控具体的文件夹就能达到同步盘的效果。
> 不过最初的目的是达到雷达一样效果的资源分享，还需要改造些地方。

企鹅号：1121114685,大佬加个好友一起交流下。
