### ISSUE TITLE
可否把“cookies.txt”文件识别目录设定为与主程序同一目录？

### ISSUE THREAD

**Issue by wocool** [gawwo/fake115-go#10]
Gawo你好：程序实际使用中带给我们非常便利的体验！但是导入时发现，如果”cookies.txt“文件不与准备导入的“.json"文件同一目录的话是无法导入的！可否把“cookies.txt”文件识别认证目录设定为与主程序同一目录？这样的话导入时就不会拘泥“.json"文件必须与”cookies.txt“文件同一目录中的限制，实现任意地方“.json"文件的导入，而不必把“.json"文件预先复制到有”cookies.txt“文件目录中才能进行导入操作。致敬！盼复！感谢！

**Comment by gawwo** [comment]
本来也是想默认读取程序同一个目录

**Comment by wocool** [comment]
也就是说我现在在系统注册表中用”fake115go"关联了"json"文件，同时修改了您共享的源码两处到关联的目录，这样“json"文件就是一个系统可执行的文件非常方便使用。感谢！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Gawo ***@***.***>
发送时间: Tuesday, May 11, 2021 9:39:30 AM
收件人: gawwo/fake115-go ***@***.***>
抄送: wocool ***@***.***>; Author ***@***.***>
主题: Re: [gawwo/fake115-go] 可否把“cookies.txt”文件识别目录设定为与主程序同一目录？ (#10)


本来也是想默认读取程序同一个目录

―
