### ISSUE TITLE
请问下 fake GO 调节线程 用什么语句？

### ISSUE THREAD

**Issue by lbcake** [gawwo/fake115-go#11]
请问下 fake GO 调节线程 用什么语句

**Comment by gawwo** [comment]
-n <number>

eg: ./fake115 -n 10

**Comment by lbcake** [comment]
> -n num
> 
> eg: ./fake115 -n 10
thx

还有在使用的时候 出现的问题  也一起在这个issues里问了哈




115://黑裙子图片 (9).jpg|3710261|CF1A61B6CDC483D3D77745A1CAB050989ADF017D|D17DFD0E48897132B02AC85A440FCF9A28394AED|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (7).jpg|3748382|796A1BED059AB3F76F89654138DAADF09EFAB892|C78B1F216ED1313AB3803B228BA996F3700C0238|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (4).jpg|3491392|13F0533AE14E2F92239A18B67F4CEC3320A71F8E|9CC493661FCDFCF795E8489559CA98A0268A9134|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (25).jpg|3714261|4342D0E423265F4B3E60D7D212A7A41D72A4A5E5|56E6CC32B24D572DC675FC5D5D65C76F332EC93A|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (24).jpg|2784798|7A0281321D90D04CA45A1602FB2DAA9ADE2523F2|88F5D8757AB59A48F3A649A1667E2C1FAFB18542|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (20).jpg|3044319|187785C7C6FCD1B81B617DE8571A5C50187DE258|9BBC8312591E0C8C9C030F2AA060DB9210AB043E|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (2).jpg|3692569|31559EE972CB3FEE923671C1DBDE214CDDD9D421|FFC1FBCDFF33653F31232A4144EBCB73DC464E1E|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (18).jpg|4025658|EA00039A5AC14F80B05C5702E7F95CCF73AA9A20|752149A2D4EC4CB4FD96DE611A5B6F8CECC3D833|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (14).jpg|3048549|254F93D6CF110EAA70E7429FA6AC64BD760D56AA|0410998B37900FCC4E93C37F66B9F41B87BC5E85|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (12).jpg|4081606|49B40E7279B197CA2CABFFA9E84FA78F6E42273A|31B586970ACD070517B8A619D6FA98A8232DE9FF|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (11).jpg|2407566|54DBE46D67DAE623413B5EA0FD73E33AE5C6F2BF|1EDF5039CD38D1874673CB3C2BE3344B221B8FEB|私人19|私人玩物 - 190727 - 黑裙子
115://黑裙子图片 (1).jpg|3165005|36C33E777445734750087E514ACB86FD06E78284|D16F76FE6826838F3B1EDA7A9F04221C8ECB4ED2|私人19|私人玩物 - 190727 - 黑裙子




以上12个文件 在导入的时候无法识别的状态   请帮忙看一下   有没有办法修复！

**Comment by gawwo** [comment]
115那边返回了异常值，你导入了的时候，当前目录有一个logs文件夹，下面的warn.log中有错误信息

**Comment by lbcake** [comment]
> 115那边返回了异常值，你导入了的时候，当前目录有一个logs文件夹，下面的warn.log中有错误信息


{"level":"warn","time":"2021-06-14 18:51:54","line":"core/importer.go:58","msg":"create dir fail","serviceName":"fake115","name":"˽\ufffd\ufffd19"



能修复成可用连接吗！

**Comment by gawwo** [comment]
文件夹名称非法字符的可以修
