### ISSUE TITLE
导入同名文件夹可以改成合并吗

### ISSUE THREAD

**Issue by zzzop** [gawwo/fake115-go#13]
现在好像是再创建一个带序号的文件夹。原因是网络原因失败的个别文件，想再次导入，不然会太多重复了。

**Comment by lbcake** [comment]
> 现在好像是再创建一个带序号的文件夹。原因是网络原因失败的个别文件，想再次导入，不然会太多重复了。

再次创建一个带序号的文件夹  很符合标准 

你的合并需求不符合正常标准
