### ISSUE TITLE
导出 数量前后不一致  丢失文件

### ISSUE THREAD

**Issue by lbcake** [gawwo/fake115-go#2]
导出一个文件夹 内含4w+文件   导出数据数量和实际数量差了10个文件   

丢失十个文件  不知道丢失的是哪十个  也么有生成错误txt文档

**Comment by gawwo** [comment]
在目录下有个logs文件夹，其中有错误日志记录。

115下载文件的时候，就有一部分文件无法下载，可能是它们把这些文件搞丢了或者文件违规。

4W+的文件，有十几个无法导出，对比平常下载115文件的情况是比较可能的。

**Comment by lbcake** [comment]
> 在目录下有个logs文件夹，其中有错误日志记录。
> 
> 115下载文件的时候，就有一部分文件无法下载，可能是它们把这些文件搞丢了或者文件违规。
> 
> 4W+的文件，有十几个无法导出，对比平常下载115文件的情况是比较可能的。

嗯 写iuss前没细看 后来都看到了。 有记录全部数据的log   还有个error log 此log里只能查到丢失的文件名

另外说下我的情况  导出4w文件 丢失十个  后续我根据文件名称一个一个定位  并且手动提取的sha1   是可以提取并且成功转存进网盘的.  并不属于115服务器搞丢或者判定违规   如果属于判定违规确实是无法提取转存  

如果时间充足可以测试一下  我觉得作者你到处数量达到70w 肯定丢失过很多文件

**Comment by gawwo** [comment]
能贴出一下对应的错误日志吗？上面记录的报错行数也有参考价值

**Comment by lbcake** [comment]
> 能贴出一下对应的错误日志吗？上面记录的报错行数也有参考价值

[warn.log](https://github.com/gawwo/fake115-go/files/5976257/warn.log)




这次的日志没看懂  总共41行 报错的文件 都可以在存入的网盘搜索到。 丢失的十个文件反而不在log里

之前导入这个json  warn-log 显示的是十个文件名   并且每个文件名在log里显示三次

**Comment by gawwo** [comment]
你这里warn log中的全是慢日志，导出太慢时有记录，估计是你网络在下载的同时还在导出。错误日志在`logs/error.log`，这里记录了导出有问题的文件。

**Comment by lbcake** [comment]
> 你这里warn log中的全是慢日志，导出太慢时有记录，估计是你网络在下载的同时还在导出。错误日志在`logs/error.log`，这里记录了导出有问题的文件。

并没有 error.log 
还有想问下这个针对同文件下 相同文件是如何处理的  过滤只取一 还是全取.

**Comment by gawwo** [comment]
以115的每个文件为单位提取，文件名称不影响是否导出。

**Comment by lbcake** [comment]
> 以115的每个文件为单位提取，文件名称不影响是否导出。


[1960106232490470381_完具少女_68GB.json.txt](https://github.com/gawwo/fake115-go/files/5982002/1960106232490470381_._68GB.json.txt)


这个实际导入 只有51G 

可以看一下

**Comment by gawwo** [comment]
那少了十多GB，按理应该导出多少，导入多少。

**Comment by lbcake** [comment]
> 那少了十多GB，按理应该导出多少，导入多少。

理论上使用没啥大问题       合并的代码 更新一个新版吧   json txt支持代码
