### ISSUE TITLE
导入提示Too much arguments  json文件5MB

### ISSUE THREAD

**Issue by montbell** [gawwo/fake115-go#4]
导入提示Too much arguments    json文件5MB      这是对导入文件json大小有要求吗

**Comment by gawwo** [comment]
对导入的json大小没有要求，这是在填写了不符合要求的命令行参数时的错误，你命令行的参数是写的什么？

**Comment by montbell** [comment]
先在网盘创建了要导入的空文件夹   找出cid   然后按照格式
fake115 cid  导入的文件.json
fake115 2040751204532140760 40872首无损歌曲 1.42T_1455GB.json
这个导入的文件是别人发我的，我发现命名不规范少了前面的原文件夹的cid值，但是里面内容没问题。

**Comment by montbell** [comment]
![image](https://user-images.githubusercontent.com/75882051/107885618-5a5ea000-6f36-11eb-8788-0c7f72d157fa.png)

**Comment by montbell** [comment]
![image](https://user-images.githubusercontent.com/75882051/107885708-d953d880-6f36-11eb-904e-8fcfd1e1ef5a.png)

**Comment by lbcake** [comment]
你这个格式 不是作者的软件导出的   肯定是导入不进去的。 虽然都是json格式

**Comment by lbcake** [comment]
> 先在网盘创建了要导入的空文件夹 找出cid 然后按照格式
> fake115 cid 导入的文件.json
> fake115 2040751204532140760 40872首无损歌曲 1.42T_1455GB.json
> 这个导入的文件是别人发我的，我发现命名不规范少了前面的原文件夹的cid值，但是里面内容没问题。

你这个格式 不是作者的软件导出的 肯定是导入不进去的。 虽然都是json格式

**Comment by montbell** [comment]
明白了，可能是用了那个GUI包装的fake115.我以为通用，不通用就可惜了

**Comment by user1121114685** [comment]
一个简单的办法，最后的json拖过去。试试吧

**Comment by gawwo** [comment]
`fake115 2040751204532140760 40872首无损歌曲 1.42T_1455GB.json`，错误原因在`40872首无损歌曲 1.42T_1455GB.json`文件名称存在空格，powershell的命令以空格分隔。解决办法：
- 把文件名的空格删除掉
- 给文件名加双引号`("")`

**Comment by montbell** [comment]
> `fake115 2040751204532140760 40872首无损歌曲 1.42T_1455GB.json`，错误原因在`40872首无损歌曲 1.42T_1455GB.json`文件名称存在空格，powershell的命令以空格分隔。解决办法任选一个：
> 
> * 把文件名的空格删除掉
> * 给文件名加双引号`("")`

非常感谢 我成功了   确实是空格的问题  
![image](https://user-images.githubusercontent.com/75882051/107965866-04493580-6fe6-11eb-88ad-02c2bc95485c.png)
