### ISSUE TITLE
cookies.txt的格式

### ISSUE THREAD

**Issue by carrionlee** [gawwo/fake115-go#8]
按照教程已经将获取的cookies放入cookies.txt中，但显示Login expire or fail...

**Comment by gawwo** [comment]
把这部分填写进去

![image](https://user-images.githubusercontent.com/19338298/111317662-504bd080-869f-11eb-82ec-0583216b23ea.png)

**Comment by gawwo** [comment]
Cookie后面，从UM开始一直复制完，保存到当前目录下的cookies.txt文件中
